import type { Metadata } from 'next'
import { Geist, Geist_Mono, Outfit } from 'next/font/google'
import Script from 'next/script'
import './globals.css'
import ThemeToggleNoSSR from '../components/theme-toggle-nossr'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

const outfit = Outfit({
    variable: '--font-outfit',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <Script id="theme-init" strategy="beforeInteractive">{`
                (function () {
                  try {
                    var theme = localStorage.getItem('theme'); // 'light' | 'dark' | null
                    var systemDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                    var shouldDark = theme === 'dark' || (theme === null && systemDark);
                    var root = document.documentElement;
                    if (shouldDark) root.classList.add('dark');
                    else root.classList.remove('dark');
                  } catch (e) {}
                })();
                `}</Script>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased`}
            >
                {children}
                <ThemeToggleNoSSR />
            </body>
        </html>
    )
}
